apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: 
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
  - stage: test
    autoPromotionEnabled: true
  - stage: preview
    autoPromotionEnabled: true
  - stage: prod-uswest
    autoPromotionEnabled: true
  - stage: prod-euwest
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/bookmanj/kargoring.git
      branch: main
  - image:
      repoURL: ghcr.io/dhpup/guestbook
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: guestbook
  annotations:
    kargo.akuity.io/color: purple
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
    warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/bookmanj/kargoring.git
      writeBranch: stage/dev
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/dev
    argoCDAppUpdates:
    - appName: guestbook-dev
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: guestbook
  annotations:
    kargo.akuity.io/color: blue
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
    upstreamStages:
    - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/bookmanj/kargoring.git
      writeBranch: stage/test
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/test
    argoCDAppUpdates:
    - appName: guestbook-test
      appNamespace: argocd
  verification:
    analysisTemplates:
    - name: guestbook-verification
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: preview
  namespace: guestbook
  annotations:
    kargo.akuity.io/color: blue
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/bookmanj/kargoring.git
      writeBranch: stage/preview
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/preview
    argoCDAppUpdates:
    - appName: guestbook-preview
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-euwest
  namespace: guestbook
  annotations:
    kargo.akuity.io/color: cyan
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
    upstreamStages:
    - name: preview
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/bookmanj/kargoring.git
      writeBranch: stage/prod-euwest
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/prod-euwest
    argoCDAppUpdates:
    - appName: guestbook-prod-euwest
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-uswest
  namespace: guestbook
  annotations:
    kargo.akuity.io/color: pink
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
    upstreamStages:
    - name: preview
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/bookmanj/kargoring.git
      writeBranch: stage/prod-uswest
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/prod-uswest
    argoCDAppUpdates:
    - appName: guestbook-prod-uswest
      appNamespace: argocd
