apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster]}
          matchLabels:
            stamp: platform
        values:
          gitver: '{{ index .metadata.labels "gitver" }}'
          stamp: '{{ index .metadata.labels "stamp" }}'
          ring: '{{ index .metadata.labels "ring" }}'
          region: '{{ index .metadata.labels "region" }}'
  template:
    metadata:
      name: guestbook-{{ .values.ring }}
      annotations:
        kargo.akuity.io/authorized-stage: guestbook:{{ .values.ring }}
    spec:
      project: kargo-demo
      source:
        repoURL: https://github.com/bookmanj/kargoring.git
        targetRevision: stage/{{ .values.ring }}
        path: guestbook/stages/{{ .values.ring }}
      destination:
        name: '{{ .name }}'
        namespace: guestbook-{{ .values.ring }}
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
