apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
        dest: platform-dev
      - stage: test
        dest: platform-test
      - stage: preview
        dest: platform-preview
      - stage: prod-euwest
        dest: platform-prod
      - stage: prod-uswest
        dest: platformus-prod
  template:
    metadata:
      name: guestbook-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: guestbook:{{stage}}
    spec:
      project: kargo-demo
      source:
        repoURL: https://github.com/bookmanj/kargoring.git
        targetRevision: stage/{{stage}}
        path: guestbook/stages/{{stage}}
      destination:
        name: "{{dest}}"
        namespace: guestbook-{{stage}}
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
